<a href="https://colab.research.google.com/github/adielwesley/SortAlgorithms/blob/master/Sort_Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Sort Algorithms**

In [0]:
import numpy as np

# Bubble Sort

In [145]:
valuesArray = np.random.randint(30, size=10)

def buble_sort(array):
  changed = True
  while (changed):
    changed = False
    for i in range(0, len(array)-1):
      if array[i] > array[i+1]:
        array[i], array[i+1] = array[i+1], array[i]
        changed = True
  return array

print(buble_sort(valuesArray))



[ 2  3  3  5  5  7  9 10 25 29]


#Insertion Sort

In [146]:
valuesArray = np.random.randint(30, size=10)

def insertion_sort(array):
  for i in range(1,len(array)):
    chosen = array[i]
    j = i-1
    while j >= 0 and chosen < array[j]:
      array[j+1] = array[j]
      j -= 1
    array[j+1] = chosen
  return array

print(insertion_sort(valuesArray))

[ 1  2  4  6  8 16 25 25 26 29]


#Merge Sort

In [148]:
valuesArray = np.random.randint(30, size=10)  

def merge_sort(array, start, end):
  if (start+1 < end):
    medium = (start + end) // 2
    merge_sort(array, start, medium)
    merge_sort(array, medium, end)
    merge(array, start, medium, end)
  return array

def merge(array, start, medium, end):
  if (end - start > 1):
    leftArray = array[start:medium].copy()
    rightArray = array[medium:end].copy()

    k = start
    i = 0
    j = 0

    while (i < leftArray.size and j < rightArray.size):
      if (leftArray[i] <= rightArray[j]):
        array[k] = leftArray[i]
        i += 1
      else:
        array[k] = rightArray[j]
        j += 1
      k += 1

    while (i < leftArray.size):
      array[k] = leftArray[i]
      i += 1
      k +=1

    while (j < rightArray.size):
      array[k] = rightArray[j]
      j += 1
      k += 1


print(merge_sort(valuesArray, 0, valuesArray.size))

[ 0  2  5  5  7  8 10 17 25 28]
